### ISSUE TITLE
add lamps to build menu

### ISSUE THREAD

**Issue by SEBArma** [Sparker95/Vindicta#200]
add lamps to build menu to have lights in base at night 
classnames:
Land_Camping_Light_F
Land_TentLamp_01_suspended_F
Land_TentLamp_01_suspended_red_F
Land_TentLamp_01_standing_F
Land_TentLamp_01_standing_red_F
Land_PortableLight_single_F
Land_PortableLight_double_F

**Comment by Sparker95** [comment]
Need to look more carefully to add lamps which don't have physics, but should be easy to do.

**Comment by SEBArma** [comment]
> Need to look more carefully to add lamps which don't have physics, but should be easy to do.

These do not have physics:
Land_TentLamp_01_suspended_F
Land_TentLamp_01_suspended_red_F
Land_TentLamp_01_standing_F
Land_TentLamp_01_standing_red_F

These do have physics:
Land_Camping_Light_F
Land_PortableLight_single_F
Land_PortableLight_double_F

**Comment by Sparker95** [comment]
I have added a couple of lights, thanks for the class name list.
