### ISSUE TITLE
TFAR: create access to radios with radio programmers

### ISSUE THREAD

**Issue by marvis999** [Sparker95/Vindicta#259]

**Comment by Sparker95** [comment]
What do you mean and is it related to us or to TFAR and what do we have to do and ~

**Comment by SEBArma** [comment]
this can be done by simply selecting the "give radio programmer to soldier" in the TFAR settings, but since we unse personal radios and not rifleman radios most of the time this seems to be a non-issue

**Comment by Sparker95** [comment]
SO it's related purely to our server settings I guess? Then we can close it?

**Comment by SEBArma** [comment]
yes i think so -

**Comment by SEBArma** [comment]
oops sorry

**Comment by marvis999** [comment]
Looks like it's fixed, closing issue.
