### ISSUE TITLE
BUILDUI: Fix highlighting

### ISSUE THREAD

**Issue by marvis999** [Sparker95/Vindicta#262]
The highlighting around objects, that tells you which object you are looking at in the build menu, is gone for some reason.

**Comment by Sparker95** [comment]
What highlighting issues do we have? Please update description.

**Comment by marvis999** [comment]
Added description. Found a clue:
Highlighting works if you launch the mission in the editor. It did **not** work on the server.

**Comment by zalexki** [comment]
@marvis999 do we still have this issue ? i think i saw streamers on servers with the highlight tho 🤔

**Comment by marvis999** [comment]
I think it's fixed. Can open a new issue if we get new reports.
