### ISSUE TITLE
AI: Enemy units stand calmly in buildings during combat right outside

### ISSUE THREAD

**Issue by marvis999** [Sparker95/Vindicta#265]
I blew up a building and there were at least two soldiers inside. They only started fighting then. They had not done anything up to that point, despite the outpost (which the building was located in) being taken over by players in the ~20 minutes before that.

**Comment by Sparker95** [comment]
So was there any combat right at that moment when you blew up the building?
If not, what would you expect them to do?

**Comment by marvis999** [comment]
Kinda solved by using danger.fsm...
