### ISSUE TITLE
Mission startup menu doesn't disappear when you click "start"

### ISSUE THREAD

**Issue by billw2012** [Sparker95/Vindicta#286]
It isn't clear it worked at all as nothing in the UI obviously changes. It should do one of:
- close the dialog entirely
- change the `Start` button to a "Ready" type message, like "Done", "Ready to play", "Complete" or whatever.
- just immediately start the mission automatically spawning you into the only available spawn location without requiring further player input (probably this is best?)

**Comment by Sparker95** [comment]
I think that you have fixed it. Now it closes the dialogue entirely, which is good enough. :)
