### ISSUE TITLE
Notification spam for towns discovered on new game start

### ISSUE THREAD

**Issue by billw2012** [Sparker95/Vindicta#287]
Not sure on the best fix, we don't need the notifications at all as 100 notifications in a row isn't useful to the player.
Perhaps a generalized solution would be to make the notification system only show notifications once it has not received one after a second or two, and then collate the ones it has received into more compact form. This is good because it indicates to the player a core mechanic early (getting intel about locations).

**Comment by marvis999** [comment]
Can reopen this if I'm wrong, but it looks like you fixed this? Haven't seen the problem again.
