### ISSUE TITLE
Crew not staying mounted

### ISSUE THREAD

**Issue by billw2012** [Sparker95/Vindicta#289]
This might be part of the general problems with garrisons relaxing too early. Regardless vic crews should stay mounted for a long time before dismounting, including in relax state. Or they should just never dismount...

**Comment by SEBArma** [comment]
the crew should never dismount when outside an outpost or airfield 

- right now apcs/ifvs are used exactly like trucks & are just parked & dismounted when ai patrols around

**Comment by billw2012** [comment]
Seems like they get out of tanks sometimes as well, Jacks stream showed this, players were just running up to get into the enemy tanks/apcs/ifvs etc.

**Comment by billw2012** [comment]
Hopefully fixed now (they *will* still dismount when in relaxed state, but relax state only happens in totally inactive areas).
