### ISSUE TITLE
Losing incognito happens too quickly/easily

### ISSUE THREAD

**Issue by billw2012** [Sparker95/Vindicta#290]
Regardless of states it should have a cooldown of at least a couple minutes. Standing in a building for 10 seconds shouldn't make you undercover again.

**Comment by marvis999** [comment]
You shouldn't be able to go undercover like that, unless the last group that spotted you got killed, or if you escaped a ~1km "wanted radius". Probably the last group got killed and that's why you went undercover

**Comment by billw2012** [comment]
Seems okay to me now.
