### ISSUE TITLE
Signatures broken

### ISSUE THREAD

**Issue by Sparker95** [Sparker95/Vindicta#295]

**Comment by Sparker95** [comment]
It seems like pbo files made by gulp-armapbo (our mission build tool) are broken. I tried packing same folder with the default arma packing tool and then signing, works without issues.

**Comment by Sparker95** [comment]
Maybe I need to provide some more fields to gulp-armapbo, or maybe we need to choose another build tool, no idea

**Comment by Sparker95** [comment]
Will leave it here in order to not forget:
https://github.com/winseros/gulp-armapbo-plugin/issues/6

**Comment by billw2012** [comment]
This is fixed, using armake + bis tools
