### ISSUE TITLE
Players are able to commandeer enemy vehicles using unorthodox means.

### ISSUE THREAD

**Issue by MaszoPok** [Sparker95/Vindicta#300]
Players can use "cheaty" methods to steal enemy armour, especially while undercover.

**Comment by SEBArma** [comment]
there are many ways of doing this like
- using ace medical to kill the crew
- glitching throught the bottom of RHS vehicles & shooting the crew
- wing arma physics to flip vehicles
unfotunately there is little that can be done from our side regarding those issues - they are problems realtaed to arma itself
