### ISSUE TITLE
Recruiting civilians is confusing.

### ISSUE THREAD

**Issue by billw2012** [Sparker95/Vindicta#302]
It's not clear what direct recruit does as there is both recruit direct to current group and recruit to the nearest camp, need to clarify that.
There might be issues with it not working sometimes? Not clear.

**Comment by MaszoPok** [comment]
Another known case with recruiting not working. On Rimmy's stream. Anomalies include use of Zeus Achilles and a full lobby of players.

**Comment by Sparker95** [comment]
His game mode thread has crashed. That's why recruit count was not working.

**Comment by Jeroen-Notenbomer** [comment]
Adding a better dialog where you can select what you want to say should help.

**Comment by billw2012** [comment]
I think its clear now
