### ISSUE TITLE
Should be able to somewhat automate recruitment after a while.

### ISSUE THREAD

**Issue by billw2012** [Sparker95/Vindicta#303]
Manual face to face recruitment is fine at the start, but is pretty boring and will just ruin pacing once player is in the mid game.  Perhaps have recruitment officers that can be added to a garrison occupying a town? They should be rare, only existing once a few towns are under player control.

**Comment by MaszoPok** [comment]
A small trickle of recruitments would help in the long run and if you ever need a whole lot you can just go around manually recruiting. Though I think it would be a little more common then proposed, people joining after hearing of your good deads ect. Perhaps later in the war effort deserters would join and along with then Intel.

**Comment by billw2012** [comment]
Yeah I also wanted them to physically join as well, such that road blocks of enemy will stop them. e.g. Car with a few recruits travels from town to join you at your camp, or they walk.

**Comment by MacTheGoon** [comment]
Could take a note from overthrow here and have a refugee center (or call it whatever you want), that you can interact and recruit from instead of running around chasing down AI.  Perhaps have it be able to recruit 1 to xx amount of recruits.

**Comment by billw2012** [comment]
I think something passive is better, not really any gameplay value in making player go to place and click thing to get recruits if there is no challenges or choices in it. More fun if you instead go to enemy area to effect the passive recruitment rate.

**Comment by billw2012** [comment]
Actually I didn't understand the recruitment mechanic, this bug is wrong.
