### ISSUE TITLE
Unexpected respawn of police forces in garrisoned Police Station

### ISSUE THREAD

**Issue by Losco-Nosciuto** [Sparker95/Vindicta#305]
I've been playing a while without capturing Police Stations, but now I did and I garrisoned 4 men to keep it safe.

After logging out, the AI Police did respawn at my garrisoned Police Station, making a massacre of my men.

I did logout and tried load the save again, with the same exact result.

My men massacred and Policemen all over the place, even tho the police station is still mine.

Note that there were no attack planned seeing the tablets, and I did save as soon as I killed the last policemen, so it was supposed to be clean or at least the attack should have just begun, if there was any.

here attached the last RPT file
[Arma3_x64_2020-01-16_17-22-23.zip](https://github.com/Sparker95/Vindicta/files/4072356/Arma3_x64_2020-01-16_17-22-23.zip)

**Comment by Sparker95** [comment]
Hi, thanks a lot.

Maybe you could share the vars.arma3profile file as well, so that I can load the saved game and see what's going on?

**Comment by Losco-Nosciuto** [comment]
Of course, but I have more than one save...is that all into the same savegame? here it is though, hope it's what you were looking for ;)
[Losco%20Nosciuto.vars.zip](https://github.com/Sparker95/Vindicta/files/4072895/Losco.20Nosciuto.vars.zip)

**Comment by marvis999** [comment]
Solved, I think?

**Comment by marvis999** [comment]
I'm pretty sure billw fixed this. If not, reopen.
