### ISSUE TITLE
Vanilla vehicles and equipment spawning with IFA3

### ISSUE THREAD

**Issue by MatrikSky** [Sparker95/Vindicta#306]
WW II (#296) factions do not have listed MRAPs and other modern stuff like GMGs, HMGs and helicopters so system spawns there vanilla equivalent like Hunters and Turrets witch don't really fit into ww2. Additional in crates and cars system spawns vanilla guns such as MXs, NVGs and Pate Carriers. The best solution to the problem would be if the // excluded types of units simply wouldn't spawn at all.

**Comment by marvis999** [comment]
Same issue as issue #228
