### ISSUE TITLE
UI freezes when dying

### ISSUE THREAD

**Issue by FleMo93** [Sparker95/Vindicta#307]
When dying the UI is freezing and you are not able to do anything. Happend two times for two different player after dying several times on different machines. These player were the host.  
The mouse is flickerung on the map between the normal mouse cursor and the rectangle map cursor.  
![20200116213411_1](https://user-images.githubusercontent.com/31365680/72560789-0fdca100-38a8-11ea-87d9-61cf766a862e.jpg)

**Comment by MaszoPok** [comment]
I believe that's an ACE bug, It happens when a player takes fatal damage. A temporary solution would be to change ACE settings so that players don't instantly die on fatal damage.

**Comment by FleMo93** [comment]
@MaszoPok will try it and give feedback. Thank you.

**Comment by Losco-Nosciuto** [comment]
My settings do exactly that. I never use insta-death, from almost 2 years, but still I got frozen in respawn map 3 times in 5/6 days, so I suppose it might help reducing chances, but not to solve the issue ;)

**Comment by Sparker95** [comment]
Most likely it's some error in BI's respawn screen. BI's code is often not without weird errors, especially related to interface controls.

I am making a custom respawn program anyway. The default BI's is overlaying text over our marker's text, so I wanted to replace it long time ago. Now this weird issue. I think it will be made this or next week.

**Comment by MaszoPok** [comment]
@Sparker95 I've only seen reports of this bug freezing arma and constant jittering between game and desktop only after ACE's most recent update, Hopefully your custom respawn will fix it nonetheless.

**Comment by Sparker95** [comment]
Yeah I'll just link their issue page about that: <https://github.com/acemod/ACE3/issues/7356>
In case something interesting is found about it

**Comment by Sparker95** [comment]
Should be fixed now, Now we have a different respawn screen.
