### ISSUE TITLE
Automatically generate campaign name

### ISSUE THREAD

**Issue by billw2012** [Sparker95/Vindicta#315]
Could be interesting, maybe funny or weird.

**Comment by Sparker95** [comment]
Or just a random number appended to default name, to avoid confusion

**Comment by billw2012** [comment]
Eh, I mean something more interesting than that, like random word combiner with suitable words. A random number is hardly going to avoid confusion, people don't remember random numbers!

**Comment by Sparker95** [comment]
I meant the case when you are lazy to type and just generate multiple campaigns and save them, as a result you have many campaigns with same name saved. But yes your argument is also valid.

**Comment by marvis999** [comment]
Done!
