### ISSUE TITLE
Impossible to claim base

### ISSUE THREAD

**Issue by Jasperdoit** [Sparker95/Vindicta#412]
I was trying to claim a base that was occupied by the enemy. I successfully wiped the opposition and went ahead to claim the base. 5 seconds after, it got claimed by the enemy. When I went to check on the map, I saw that there were 4 soldiers left, which there weren't as I checked via Zeus. The footage should explain the rest. I was using the latest version of Vindicta (0.34.69) when experiencing this issue.

https://streamable.com/4mxta

[Arma3_x64_2020-02-20_18-15-14.zip](https://github.com/Sparker95/Vindicta/files/4232427/Arma3_x64_2020-02-20_18-15-14.zip)

**Comment by billw2012** [comment]
Should be fixed in 0.35
