### ISSUE TITLE
OPFOR ai can be added to your squad

### ISSUE THREAD

**Issue by Jasperdoit** [Sparker95/Vindicta#414]
So, I was minding my own business, taking a PD with a buddy of mine when I come across a policeman. I shut off the alarm and saw the button "Add unit to group". I pressed it and shortly after see his marker on my screen and he proceeds to kill all the other police officers inside the compound. I was honestly laughing when I saw this happen. I believe this behavior is not supposed the occur.

Video: https://streamable.com/bpgej

[Arma3_x64_2020-02-21_15-08-18.zip](https://github.com/Sparker95/Vindicta/files/4236824/Arma3_x64_2020-02-21_15-08-18.zip)

**Comment by marvis999** [comment]
Can no longer ace interact with enemies. Will refine this in the future
