### ISSUE TITLE
Make QRFs disembark further away

### ISSUE THREAD

**Issue by marvis999** [Sparker95/Vindicta#418]
I can't count the no. of trucks I've torched with an RPG because they drive right up to their destination.
If they move in a truck they should disembark 600m away at least, then walk the rest, ideally in a line formation. Would make them that much more effective.

**Comment by billw2012** [comment]
They are meant to do this, attack CmdrAction gives attack goal to garrison with radius set. The radius is where they are meant to disembark.

**Comment by marvis999** [comment]
I'll have to debug this then

**Comment by marvis999** [comment]
Closing this until I have found a more specific problem
