### ISSUE TITLE
Shouldn't be using airdrop crates everywhere

### ISSUE THREAD

**Issue by billw2012** [Sparker95/Vindicta#446]
Its weird that police store their gear in airdrop crates! Should look for some nicer more sensible models.

**Comment by l3ackEyeD** [comment]
Big crate wise there is not really a better option. Nearly all of them have some kind of netting around them. So they look similiar

**Comment by Sparker95** [comment]
I have left only small cargo crates at police stations, I think it makes sense now?

**Comment by Sparker95** [comment]
closing for now
