### ISSUE TITLE
Add auto-save at camp

### ISSUE THREAD

**Issue by billw2012** [Sparker95/Vindicta#517]
When game hasn't been saved for x time, and all players are within 250m of camp and no enemies are, auto save.

**Comment by billw2012** [comment]
Perhaps do it when first player leaves camp range in these conditions? This would help ensure it saves after players have done their selecting loadouts/stashing stuff etc.

**Comment by Ricky1334** [comment]
Yes please billw2012 a auto save feature would be greatly appreciated as I myself haven't saved for 30mins and I've been back and forth from secure own bases and the game has quit on its own as expected with alpha stage games/mods good ideas here nice work so far

**Comment by billw2012** [comment]
Auto save has been a feature for ages, I think this issue can be closed in fact. Check out the FAQ / guide @Ricky1334 for instructions on using autosave.
