### ISSUE TITLE
createUnit is slower when defining position

### ISSUE THREAD

**Issue by Jeroen-Notenbomer** [Sparker95/Vindicta#53]
https://github.com/Sparker95/Project_0/blob/2dc8418d85dfc692058b685ab677d8e67e7466ce/Project_0.Altis/Unit/Unit.sqf#L222
https://github.com/Sparker95/Project_0/blob/2dc8418d85dfc692058b685ab677d8e67e7466ce/Project_0.Altis/Unit/Unit.sqf#L239

Might want to change this to  _groupHandle createUnit [_className, **[0,0,0]**, [], 10, "FORM"]
Createvehicle with [0,0,0] takes 0.04ms
Createvehicle with non-[0,0,0] takes 1ms (because it searches for good location).

You already do _objectHandle setPos _pos; in the end so it doesnt change anything.

Also you should probably use setPosASL/setPosATL as setPos uses nearest surface. This causes units that are stored on top of buildings (getpos is 0) to spawn under the building.
https://community.bistudio.com/wiki/Position#Formats

**Comment by Sparker95** [comment]
I am pretty sure that the current setPos format matches how I store spawn positions in first place. Otherwise the static weapons would be spawning under buildings. Also sentries spawn in buildings properly now, as I know.

As for the rest, I'll check it later.

**Comment by Sparker95** [comment]
I think it's good now
