### ISSUE TITLE
Faction: features which don't work in faction files

### ISSUE THREAD

**Issue by MatrikSky** [Sparker95/Vindicta#533]
Marvis added a feature that would automatically spawn static HMGs if the GMGs were commented out in the mission file but it isn't working, the system is still spawning GMGs.
`//_veh set [T_VEH_stat_HMG_high, []];`

Marvis added the ability for faction makers to change unit descriptions in faction templates but this isn't working too. When you make a new campaign the renamed unit will have name completely different to the one chosen.
`//(T_NAMES select T_VEH) set [T_VEH_default, "Unknown Vehicle"]; //					= 0` 

`//(T_NAMES select T_VEH) set [T_VEH_car_unarmed, "Unarmed Car"]; //					= 1 Car like a Prowler or UAZ`

`//(T_NAMES select T_VEH) set [T_VEH_car_armed, "Armed Car"]; //						= 2 Car with any kind of mounted weapon`

`//(T_NAMES select T_VEH) set [T_VEH_MRAP_unarmed, "Unarmed MRAP"]; //				= 3 MRAP`

`//(T_NAMES select T_VEH) set [T_VEH_MRAP_HMG, "HMG MRAP"]; //					= 4 MRAP with a mounted HMG gun`

`//(T_NAMES select T_VEH) set [T_VEH_MRAP_GMG, "GMG MRAP"]; //					= 5 MRAP with a mounted GMG gun`

`//(T_NAMES select T_VEH) set [T_VEH_IFV, "IFV"]; //									= 6 Infantry fighting vehicle`

`//(T_NAMES select T_VEH) set [T_VEH_APC, "APC"]; //								= 7 Armored personnel carrier`

`//(T_NAMES select T_VEH) set [T_VEH_MBT, "MBT"]; //								= 8 Main Battle Tank`

`//(T_NAMES select T_VEH) set [T_VEH_MRLS, "MRLS"]; //								= 9 Multiple Rocket Launch System`
etc.

**Comment by Sparker95** [comment]
I think we should rethink how we make factions and what is inherited from default faction.
