### ISSUE TITLE
Hidden terrain objects are being processed by the location creation script

### ISSUE THREAD

**Issue by Sparker95** [Sparker95/Vindicta#56]
For instance if you create a location which has hidden military objects inside it, the current script is still going to add spawn positions from the hidden buildings. It will cause static guns to spawn there, for instance.

**Comment by SEBArma** [comment]
the same issue happens with bills new base construction feature, turrets spawn in (hidden) towers when the base is not constructed - then they fall to the ground

**Comment by billw2012** [comment]
Yeah this is easy to fix, I already did it for units. Not sure what to do with statics that don't have spawn locations though. Spawning them on the road is going to be silly! We need hidden buildings we can use to place these on the grounds as well.

**Comment by billw2012** [comment]
Well this is fixed, hidden buildings are not used to spawn statics. It defaults then to just spawning them on the road, but this is a different issue.
