### ISSUE TITLE
Save custom map markers

### ISSUE THREAD

**Issue by billw2012** [Sparker95/Vindicta#609]

**Comment by Sparker95** [comment]
What does it mean?

**Comment by billw2012** [comment]
If player adds markers on the map then save them. They aren't currently right?

**Comment by Sparker95** [comment]
Correct, they are not. Haven't seen it done but as I know they can be accessed and therefore serialized and deserialized. Also there is some BIS_fnc which does serialization and deserialization of markers, was added maybe less than a year ago.

**Comment by billw2012** [comment]
Fixed in 7f3a855ac4bf1e656caefc97ef6bbb32263af648
