### ISSUE TITLE
Add Stringtable.xml

### ISSUE THREAD

**Issue by teemo0803** [Sparker95/Vindicta#629]
HI,
Would you mind adding a so called stringtable.xml file to set up the translate frame.Since im only a sqf noob,i simply know how to add translations into the xml file.It will have lots of player if it has Chinese version and i can add it.Thanks for replying.
Yours,
Teemo

**Comment by Sparker95** [comment]
Hi Teemo.

Some strings are not finalized yet.
Also now we are focusing on other things, and I don't know when anyone will be free and willing to convert all strings to stringtable.

If you would like to add stringtable yourself, go ahead.

**Comment by teemo0803** [comment]
alright,i'll try to figure out.
thanks,
teemo

**Comment by Sparker95** [comment]
Sure, you can reach us at discord:
https://discord.gg/fqemtaB
