### ISSUE TITLE
Improve Garrison 'move unmounted' action

### ISSUE THREAD

**Issue by Sparker95** [Sparker95/Vindicta#64]
Now it moves linearly, we would prefer it to move on the road with the virtual route.
Also spawned garrison should get waypoints from virtual route.
To make it happen, we must improve waypoint handling in virtual route: https://github.com/Sparker95/Project_0/blob/276293d1cbf02757c479e9a10535efc14e8d382b/Project_0.Altis/AI/VirtualRoute/VirtualRoute.sqf#L126

**Comment by billw2012** [comment]
This is fixed.
