### ISSUE TITLE
BUG CHANGE TIME

### ISSUE THREAD

**Issue by teemo0803** [Sparker95/Vindicta#646]
![image](https://user-images.githubusercontent.com/49296645/85191447-849d8680-b2f1-11ea-8923-8b28cf4f1dbe.png)

Every player can change time, this may cause chaos

**Comment by Sparker95** [comment]
Thanks for reporting this. It's quite easy to fix.

**Comment by Sparker95** [comment]
Fixed in https://github.com/Sparker95/Vindicta/commit/38835e9dce8bfb3df3e1338b6bd82970545aa631.
