### ISSUE TITLE
Arsenal duplication bug

### ISSUE THREAD

**Issue by Sparker95** [Sparker95/Vindicta#649]
you select an item in the arsenal - it gets added to your player - you de-select it again by clicking on another item - if you do it fast the items duplicate - if multiple people do it it works better

Perhaps it only happens when many people access same arsenal.

Also the game might freeze a bit when this happens.

**Comment by Lazejun** [comment]
Depends on how you look at it, if its the same way i know of its Converting items over.

As soon as your Reach 0 and you keep on clicking its "Duplicating" or more Creating new weapons.

This happens with all weapons that con Convert -------> RHS Weapons that change Classnames based on Frontgrip.
CBA Launchers as the NLAW that change from the Bohemia Interactive version "launch_NLAW_F" into the CBA/ACE version.
I once Mentioned it to Jeroen when i had the Time but he told me: "You should not be able to grab a Weapon thats on 0".

**Comment by Sparker95** [comment]
Fixed it some time ago, forgot to close.
