### ISSUE TITLE
Russian 2035 faction dependency issues

### ISSUE THREAD

**Issue by Sparker95** [Sparker95/Vindicta#655]
It doesn't declare RHSGREF as dependency, although it uses some of its vehicles.

**Comment by tastesliketriangle** [comment]
My suggestion would be to remove the dependency altogether. it only use 2 vehicles, which is very wasteful considering the size of all the RHS components you would need.

#656

**Comment by Sparker95** [comment]
Hi, thanks, yes the faction author Jasper has approved that these can be removed.
