### ISSUE TITLE
Mission Crash

### ISSUE THREAD

**Issue by Zeata** [Sparker95/Vindicta#695]
as of the update yesterday, we get a mission crash

we first tried our mission which we were about 6 hours in, and that crashed after about 20 minutes. so we started a new mission in the hopes that it was just the save that wasn't compatible, this one crashed after about an hour

the RPT files are in the zip

[vindictaCrash.zip](https://github.com/Sparker95/Vindicta/files/5038732/vindictaCrash.zip)

**Comment by Sparker95** [comment]
Hi!

Thanks for your report. I have just pushed an update which fixes this.
