### ISSUE TITLE
Tembelan Island Update

### ISSUE THREAD

**Issue by Serverfrog** [Sparker95/Vindicta#707]
I tried to use Tembelan Island but when it's starts at the client an Error Pops Up
"vindicta_missions\vindicta_tembelan.tembelan\mission.sqm/Mission/Entities/Item49.type: Behicle class Vindicta_LocationWaypoint no longer exists"

I tried other Maps like Malden and there it is working perfectly fine.

Mods that are Running there:

- Advanced Towing
- VET_Unflipping
- Boxloader
- Boxloader - ACE Comp
- GRAD Trenches
- Immersion Cigs
- Enhanced Movement
- ACE
- ACEX
- CBA
- Vindicta

**Comment by Sparker95** [comment]
So I guess it works for you?

**Comment by Serverfrog** [comment]
I tested it a bit, and beside that the Side to choose are the Debug Slots in the beginning i didn't find any crashes or errors, but im a pretty beginner in Arma Server setups ;)

**Comment by Sparker95** [comment]
I guess we can close this then 👍
