### ISSUE TITLE
Flip static weapon upright when its being crewed by AI

### ISSUE THREAD

**Issue by SomethingSimpl** [Sparker95/Vindicta#741]
ActionUnitGetInVehicle - method "Activate".
Check if vehicle is a static and do setVectorUp on it to make the statics as consistent as possible.

**Comment by Sparker95** [comment]
You've got to add it somewhere here:
https://github.com/Sparker95/Vindicta/blob/3e6793801e11edf83392fcd3eb8fd01e46a8603b/src/AI/Unit/ActionUnitGetInVehicle.sqf#L169
_unitVeh is the OOP object associated with the target vehicle the bot is ordered to get in. You can check if it's a static weapon like this:
`if(CALLM0(_unitVeh, "isStatic") then { ...  };`

https://github.com/Sparker95/Vindicta/blob/3e6793801e11edf83392fcd3eb8fd01e46a8603b/src/AI/Unit/ActionUnitGetInVehicle.sqf#L155
The `_hO` is an arma vehicle object handle, that's the thing on which you will do setVectorUp and such.

**Comment by SomethingSimpl** [comment]
solved in #743

**Comment by Sparker95** [comment]
Awesome, thank you!
