### ISSUE TITLE
description.ext editing.

### ISSUE THREAD

**Issue by Pesoen** [Sparker95/Vindicta#777]
i want to add a radio mod, but i want to add the "Addon-Free ArmA Radio" which requires me to edit the description.ext to add a few lines, but it looks either encrypted or binarized. anyway to get the few lines added, i don't care if it stays binarized, so long as i get a description.ext with the required lines in it, so the AFAR script works.

the reason for this, is that most players just refuse to join teamspeak, and prefer to sit on discord while playing(something i catch myself doing as well) and i wanted to insert this into the game, as it then just uses regular ingame comms, instead of needing to start up teamspeak, like tfar or ACRE2 requires.. might help make people actually use the ingame radio instead of discord, since there is no real effort required.

**Comment by Jasperdoit** [comment]
Are you trying to modify the gamemode straight from the compiled version (Steam release)? You can download the repository, make your edit and compile it afterwards too. AFAIK the description.ext isn't binarized on the development branch.

**Comment by Sparker95** [comment]
Jasperdoit is right. You should not try to modify the packed files if they are binarized. Instead you should download the repository from Github and use these instructions to build the .pbo files after you ahve modified description.ext:
https://github.com/Sparker95/Vindicta/wiki/DEV-Setup

**Comment by Pesoen** [comment]
got it, that was my mistake it seems. thanks for the help :)
