### ISSUE TITLE
Absolutely overkill stringtable error spam

### ISSUE THREAD

**Issue by dedmen** [Sparker95/Vindicta#789]
Here is a short excerpt of RPT log at Arma or Arma server startup.

> 11:20:02 Item STR_JNA_ACT_CONTAINER_OPEN listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_JNA_ACT_CONTAINER_OPEN_DESC listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_JNA_ACT_UNLOAD listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_JNA_ACT_UNLOAD_DESC listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_JNA_ACT_CONTAINER_SELECTERROR1 listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_JNA_ACT_CONTAINER_SELECTERROR2 listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_JNA_ACT_CONTAINER_SELECTERROR3 listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_JNG_ACT_OPEN listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_JNG_ACT_STOREVEHICLE listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_JNG_ACT_CONTAINER_SELECTERROR1 listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_JNG_ACT_CONTAINER_SELECTERROR2 listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_JN_FUEL_ACT_REFUEL listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_JN_FUEL_ACT_REFUELOPTION listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_JN_FUEL_ACT_FUELTANK listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_JN_FUEL_ACT_FUELCARGO listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_JN_AMMO_ACT_REARM listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_JN_REPAIR_ACT_REPAIR listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_UM_OVERT listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_UM_SUSPICIOUS listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_UM_UNDERCOVER listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml
11:20:02 Item STR_UM_COMPROMISED listed twice
11:20:02  ➥ Context: vindicta_missions\vindicta_tanoa.tanoa\stringtable.xml

Here is the full excerpt:
[VindictaErrorSpam.txt](https://github.com/Sparker95/Vindicta/files/6212493/VindictaErrorSpam.txt)

I think this happens because all these strings are already defined in the main stringtable.
But you have copies of it in each mission so each mission tries to set strings that were already set.

**Comment by Sparker95** [comment]
Hi, thanks for the report!

> I think this happens because all these strings are already defined in the main stringtable.
But you have copies of it in each mission so each mission tries to set strings that were already set.
But we don't have the main stringtable. Each stringtable lies within its own mission within the pbo file. I assumed that stringtable inside a given mission folder is supposed to work only within this given mission.

That's how the file structure looks like:
![image](https://user-images.githubusercontent.com/8287316/112726952-0bdaf300-8f31-11eb-8904-aeb0116d57aa.png)

Where should I put the stringtable then so that it doesn't complain? Or is it an arma bug after all?

**Comment by dedmen** [comment]
If you have a Arma mod anyway. 
You could just put the stringtable into there once.
Instead of having duplicates in each mission?

**Comment by Sparker95** [comment]
Yes, but I assumed it would be better to have them in mission so that they have mission scope instead of polluting the stringtable for every other mod. I don't know how it works internally, I guess either way it gets added to the global stringtable then, right? Otherwise it wouldn't complain in the log file

**Comment by Sparker95** [comment]
Fixed at https://github.com/Sparker95/Vindicta/commit/00f52379fb070ba34b702f8537a66d64742dc58f
I've moved the stringtable file to the mod root.
