### ISSUE TITLE
Livonia doesn't work on a dedicated server

### ISSUE THREAD

**Issue by wriley** [Sparker95/Vindicta#802]
When running the Livonia mission on a dedicated server the player loads in on police side. All intel is given on map view before loading in and police ignore you even if you shoot them. Livonia works fine as a single player scenario. Altis and Malden work fine on the same server.

Version: 0.55.45

Thanks for an awesome mod!

Screenshots and RPT attached
[arma3server_x64_2021-06-22_14-53-01.zip](https://github.com/Sparker95/Vindicta/files/6697068/arma3server_x64_2021-06-22_14-53-01.zip)
![20210622144905_1](https://user-images.githubusercontent.com/532318/122991188-5de1b800-d36a-11eb-8b85-2416e74fe034.jpg)
![20210622144959_1](https://user-images.githubusercontent.com/532318/122991237-6a661080-d36a-11eb-9495-aa6957daf45d.jpg)
![20210622145013_1](https://user-images.githubusercontent.com/532318/122991263-6f2ac480-d36a-11eb-8012-6dcc14b1ec98.jpg)

**Comment by Lazejun** [comment]
Well its not realy an Issue,

Due to Slot order placed in the Mission, the first slots to show will be IND.

IND are Debug/Admin Slots, not intended to be Played on.

You could just take the Bluefor Slots as you are Supposed to.

**Comment by wriley** [comment]
Derp! I've played this on 3-4 other maps and never noticed the default faction was wrong on Livonia. Thank you for the quick response
