### ISSUE TITLE
Add vehicles in town

### ISSUE THREAD

**Issue by Jeroen-Notenbomer** [Sparker95/Vindicta#94]
We need vehicles in towns for us to steal.

I guess they can be placed randomly for now because when you move away and comeback civilians could have driven around.

**Comment by Jeroen-Notenbomer** [comment]
Need some ideas of how to place them like:
parallel next to road, next to buildings.
and some algorithms

**Comment by billw2012** [comment]
https://github.com/billw2012/A3-Antistasi/commit/59edbdbfae4d0176c44c148bb6b90fae0c1da966
Where is what I did for my own antistasi branch.

**Comment by Sparker95** [comment]
The module we used for civilians uses some method of spawning them in areas not observed by anyone I think? Maybe we could adapt it to vehicles too?

**Comment by zalexki** [comment]
the more realistic the better i guess, so i would make them spawn in garages, inside gardens with double doors, or near house maybe like half on road, half offroad but always close to houses.
Dunno how much we control we have on this tho

**Comment by Sparker95** [comment]
Bill has added vehicles already by making civilian garrisons and it works pretty well, also it makes civilian vehicles limited in towns.

We still need to implement civilians which drive around.
